version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.1
    - 4.6.3
    - 4.6.4
  - dependency-name: symfony/string
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/console
    versions:
    - 5.2.3
  - dependency-name: felixfbecker/advanced-json-rpc
    versions:
    - 3.2.0
  - dependency-name: amphp/amp
    versions:
    - 2.5.2
