language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.4

before_script:
  - composer install
  - git config --global user.email "ocramius+travis-ci@gmail.com"
  - git config --global user.name "Marco Pivetta (via Travis-CI)"

script:
  - vendor/bin/phpcs
  - vendor/bin/psalm
  - vendor/bin/phpunit
  - vendor/bin/infection --min-msi=99 --min-covered-msi=100
  - php build-conflicts.php
  - vendor/bin/roave-no-leaks
  - mkdir -p /tmp/dependency-check && composer require --dev -d/tmp/dependency-check maglnet/composer-require-checker:^2.1.0 && /tmp/dependency-check/vendor/bin/composer-require-checker check composer.json
