language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1

before_script:
  - composer install
  - git config --global user.email "ocramius+travis-ci@gmail.com"
  - git config --global user.name "Marco Pivetta (via Travis-CI)"

script:
  - vendor/bin/phpunit
  - php build-conflicts.php
