name: Quality check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Code sniffer
        run: vendor/bin/phpcs

      - name: Psalm
        run: vendor/bin/psalm

      - name: Phpunit
        run: vendor/bin/phpunit

      - name: Mutation testing
        run: vendor/bin/infection --min-msi=99 --min-covered-msi=100

      - name: Memory leaks detection
        run: vendor/bin/roave-no-leaks

      - name: Composer Require Checker
        run: vendor/bin/composer-require-checker check composer.json
